/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_SIGNAL                             TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_SIGNAL                             RX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/* GPIO_AD_B0_09 (coord F14), JTAG_TDI/J21[5]/ENET_RST/J22[5] */
/* Routed pin properties */
#define BOARD_INITLEDS_BOARD_LED_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITLEDS_BOARD_LED_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITLEDS_BOARD_LED_CHANNEL                                      9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_BOARD_LED_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITLEDS_BOARD_LED_GPIO_PIN                                     9U   /*!< GPIO pin number */
#define BOARD_INITLEDS_BOARD_LED_GPIO_PIN_MASK                        (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITLEDS_BOARD_LED_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITLEDS_BOARD_LED_PIN                                          9U   /*!< PORT pin number */
#define BOARD_INITLEDS_BOARD_LED_PIN_MASK                             (1U << 9U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), AUD_INT/CSI_D9//J35[13]/J22[4] */
/* Routed pin properties */
#define BOARD_INITLEDS_RED_LED_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITLEDS_RED_LED_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITLEDS_RED_LED_CHANNEL                                       24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_RED_LED_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITLEDS_RED_LED_GPIO_PIN                                      24U   /*!< GPIO pin number */
#define BOARD_INITLEDS_RED_LED_GPIO_PIN_MASK                         (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITLEDS_RED_LED_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITLEDS_RED_LED_PIN                                           24U   /*!< PORT pin number */
#define BOARD_INITLEDS_RED_LED_PIN_MASK                              (1U << 24U)   /*!< PORT pin mask */

/* GPIO_AD_B1_09 (coord M13), SAI1_MCLK/CSI_D8/J35[11] */
/* Routed pin properties */
#define BOARD_INITLEDS_GREEN_LED_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITLEDS_GREEN_LED_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITLEDS_GREEN_LED_CHANNEL                                     25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_GREEN_LED_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITLEDS_GREEN_LED_GPIO_PIN                                    25U   /*!< GPIO pin number */
#define BOARD_INITLEDS_GREEN_LED_GPIO_PIN_MASK                       (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITLEDS_GREEN_LED_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITLEDS_GREEN_LED_PIN                                         25U   /*!< PORT pin number */
#define BOARD_INITLEDS_GREEN_LED_PIN_MASK                            (1U << 25U)   /*!< PORT pin mask */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
/* Routed pin properties */
#define BOARD_INITLEDS_BLUE_LED_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITLEDS_BLUE_LED_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITLEDS_BLUE_LED_CHANNEL                                      10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_BLUE_LED_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITLEDS_BLUE_LED_GPIO_PIN                                     10U   /*!< GPIO pin number */
#define BOARD_INITLEDS_BLUE_LED_GPIO_PIN_MASK                        (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITLEDS_BLUE_LED_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITLEDS_BLUE_LED_PIN                                          10U   /*!< PORT pin number */
#define BOARD_INITLEDS_BLUE_LED_PIN_MASK                             (1U << 10U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLeds(void);

/* GPIO_AD_B0_05 (coord G14), CAN_STBY/BOOT_MODE[1]/Flash_RST/U12[8] */
/* Routed pin properties */
#define BOARD_INITKEYS_CAN_STBY_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITKEYS_CAN_STBY_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITKEYS_CAN_STBY_CHANNEL                                       5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITKEYS_CAN_STBY_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITKEYS_CAN_STBY_GPIO_PIN                                      5U   /*!< GPIO pin number */
#define BOARD_INITKEYS_CAN_STBY_GPIO_PIN_MASK                         (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITKEYS_CAN_STBY_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITKEYS_CAN_STBY_PIN                                           5U   /*!< PORT pin number */
#define BOARD_INITKEYS_CAN_STBY_PIN_MASK                              (1U << 5U)   /*!< PORT pin mask */

/* WAKEUP (coord L6), SD_PWREN */
/* Routed pin properties */
#define BOARD_INITKEYS_SD_PWREN_PERIPHERAL                                 GPIO5   /*!< Peripheral name */
#define BOARD_INITKEYS_SD_PWREN_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITKEYS_SD_PWREN_CHANNEL                                       0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITKEYS_SD_PWREN_GPIO                                       GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITKEYS_SD_PWREN_GPIO_PIN                                      0U   /*!< GPIO pin number */
#define BOARD_INITKEYS_SD_PWREN_GPIO_PIN_MASK                         (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITKEYS_SD_PWREN_PORT                                       GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_INITKEYS_SD_PWREN_PIN                                           0U   /*!< PORT pin number */
#define BOARD_INITKEYS_SD_PWREN_PIN_MASK                              (1U << 0U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitKeys(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2c1(void);

/* GPIO_EMC_40 (coord A7), ENET_MDC */
/* Routed pin properties */
#define BOARD_INPUTCAP_ENET_MDC_PERIPHERAL                                  GPT2   /*!< Peripheral name */
#define BOARD_INPUTCAP_ENET_MDC_SIGNAL                               gpt_capture   /*!< Signal name */
#define BOARD_INPUTCAP_ENET_MDC_CHANNEL                                       2U   /*!< Signal channel */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InputCap(void);

/* GPIO_AD_B1_11 (coord J13), SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2] */
/* Routed pin properties */
#define BOARD_INITADC_CSI_D6_PERIPHERAL                                     ADC1   /*!< Peripheral name */
#define BOARD_INITADC_CSI_D6_SIGNAL                                           IN   /*!< Signal name */
#define BOARD_INITADC_CSI_D6_CHANNEL                                          0U   /*!< Signal channel */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitAdc(void);

/* GPIO_AD_B0_15 (coord L10), CAN2_RX/U12[4] */
/* Routed pin properties */
#define BOARD_INITCAN_CAN2_RX_PERIPHERAL                                    CAN2   /*!< Peripheral name */
#define BOARD_INITCAN_CAN2_RX_SIGNAL                                          RX   /*!< Signal name */

/* GPIO_AD_B0_14 (coord H14), CAN2_TX/U12[1] */
/* Routed pin properties */
#define BOARD_INITCAN_CAN2_TX_PERIPHERAL                                    CAN2   /*!< Peripheral name */
#define BOARD_INITCAN_CAN2_TX_SIGNAL                                          TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCan(void);

/* GPIO_EMC_00 (coord E3), SEMC_D0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D0_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_01 (coord F3), SEMC_D1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D1_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_02 (coord F4), SEMC_D2 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D2_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D2_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_03 (coord G4), SEMC_D3 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D3_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D3_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_04 (coord F2), SEMC_D4 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D4_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D4_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D4_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_EMC_05 (coord G5), SEMC_D5 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D5_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D5_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D5_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_EMC_06 (coord H5), SEMC_D6 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D6_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D6_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D6_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_EMC_07 (coord H4), SEMC_D7 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D7_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D7_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D7_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_EMC_30 (coord C6), SEMC_D8 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D8_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D8_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D8_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_EMC_31 (coord C5), SEMC_D9 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D9_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D9_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D9_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_EMC_32 (coord D5), SEMC_D10 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D10_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D10_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D10_CHANNEL                                     10U   /*!< Signal channel */

/* GPIO_EMC_33 (coord C4), SEMC_D11 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D11_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D11_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D11_CHANNEL                                     11U   /*!< Signal channel */

/* GPIO_EMC_34 (coord D4), SEMC_D12 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D12_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D12_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D12_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_EMC_35 (coord E5), SEMC_D13 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D13_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D13_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D13_CHANNEL                                     13U   /*!< Signal channel */

/* GPIO_EMC_36 (coord C3), SEMC_D14 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D14_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D14_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D14_CHANNEL                                     14U   /*!< Signal channel */

/* GPIO_EMC_37 (coord E4), SEMC_D15 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D15_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D15_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D15_CHANNEL                                     15U   /*!< Signal channel */

/* GPIO_EMC_09 (coord C2), SEMC_A0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A0_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_10 (coord G1), SEMC_A1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A1_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_11 (coord G3), SEMC_A2 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A2_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A2_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_12 (coord H1), SEMC_A3 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A3_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A3_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_13 (coord A6), SEMC_A4 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A4_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A4_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A4_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_EMC_14 (coord B6), SEMC_A5 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A5_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A5_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A5_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_EMC_15 (coord B1), SEMC_A6 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A6_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A6_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A6_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_EMC_16 (coord A5), SEMC_A7 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A7_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A7_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A7_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_EMC_17 (coord A4), SEMC_A8 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A8_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A8_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A8_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_EMC_18 (coord B2), SEMC_A9 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A9_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A9_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A9_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_EMC_23 (coord G2), SEMC_A10 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A10_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A10_SIGNAL                                     ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A10_CHANNEL                                     10U   /*!< Signal channel */

/* GPIO_EMC_19 (coord B4), SEMC_A11 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A11_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A11_SIGNAL                                     ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A11_CHANNEL                                     11U   /*!< Signal channel */

/* GPIO_EMC_20 (coord A3), SEMC_A12 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A12_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A12_SIGNAL                                     ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A12_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_EMC_39 (coord B7), SEMC_DQS */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_DQS_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_DQS_SIGNAL                                 semc_dqs   /*!< Signal name */

/* GPIO_EMC_21 (coord C1), SEMC_BA0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_BA0_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_BA0_SIGNAL                                       BA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_BA0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_EMC_22 (coord F1), SEMC_BA1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_BA1_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_BA1_SIGNAL                                       BA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_BA1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_EMC_25 (coord D2), SEMC_RAS */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_RAS_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_RAS_SIGNAL                                 semc_ras   /*!< Signal name */

/* GPIO_EMC_24 (coord D3), SEMC_CAS */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CAS_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CAS_SIGNAL                                 semc_cas   /*!< Signal name */

/* GPIO_EMC_28 (coord D1), SEMC_WE */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_WE_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_WE_SIGNAL                                   semc_we   /*!< Signal name */

/* GPIO_EMC_08 (coord H3), SEMC_DM0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_DM0_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_DM0_SIGNAL                                       DM   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_DM0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_EMC_38 (coord D6), SEMC_DM1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_DM1_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_DM1_SIGNAL                                       DM   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_DM1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_EMC_27 (coord A2), SEMC_CKE */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CKE_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CKE_SIGNAL                                 semc_cke   /*!< Signal name */

/* GPIO_EMC_26 (coord B3), SEMC_CLK */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CLK_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CLK_SIGNAL                                 semc_clk   /*!< Signal name */

/* GPIO_EMC_29 (coord E1), SEMC_CS0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CS0_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CS0_SIGNAL                                       CS   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_CS0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_INITSDRAM_ENET_MDIO_PERIPHERAL                                SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_ENET_MDIO_SIGNAL                                     CSX   /*!< Signal name */
#define BOARD_INITSDRAM_ENET_MDIO_CHANNEL                                     0U   /*!< Signal channel */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSdram(void);

/* GPIO_SD_B0_01 (coord J3), SD1_CLK/J24[3] */
/* Routed pin properties */
#define BOARD_USDHC_SD1_CLK_PERIPHERAL                                    USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD1_CLK_SIGNAL                                     usdhc_clk   /*!< Signal name */

/* GPIO_SD_B0_00 (coord J4), SD1_CMD/J24[6] */
/* Routed pin properties */
#define BOARD_USDHC_SD1_CMD_PERIPHERAL                                    USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD1_CMD_SIGNAL                                     usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
/* Routed pin properties */
#define BOARD_USDHC_SD1_D0_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD1_D0_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_USDHC_SD1_D0_CHANNEL                                            0U   /*!< Signal channel */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
/* Routed pin properties */
#define BOARD_USDHC_SD1_D1_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD1_D1_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_USDHC_SD1_D1_CHANNEL                                            1U   /*!< Signal channel */

/* GPIO_SD_B0_04 (coord H2), SD1_D2 */
/* Routed pin properties */
#define BOARD_USDHC_SD1_D2_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD1_D2_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_USDHC_SD1_D2_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_SD_B0_05 (coord J2), SD1_D3 */
/* Routed pin properties */
#define BOARD_USDHC_SD1_D3_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD1_D3_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_USDHC_SD1_D3_CHANNEL                                            3U   /*!< Signal channel */

/* GPIO_B1_14 (coord C14), SD0_VSELECT */
/* Routed pin properties */
#define BOARD_USDHC_SD0_VSELECT_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_USDHC_SD0_VSELECT_SIGNAL                             usdhc_vselect   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_USDHC(void);

/* GPIO_SD_B1_06 (coord L3), FlexSPI_SS0 */
/* Routed pin properties */
#define BOARD_INITFLEXSPI_FlexSPI_SS0_PERIPHERAL                         FLEXSPI   /*!< Peripheral name */
#define BOARD_INITFLEXSPI_FlexSPI_SS0_SIGNAL                     FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
/* Routed pin properties */
#define BOARD_INITFLEXSPI_FlexSPI_D0_A_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITFLEXSPI_FlexSPI_D0_A_SIGNAL                    FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
/* Routed pin properties */
#define BOARD_INITFLEXSPI_FlexSPI_D1_A_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITFLEXSPI_FlexSPI_D1_A_SIGNAL                    FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
/* Routed pin properties */
#define BOARD_INITFLEXSPI_FlexSPI_D2_A_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITFLEXSPI_FlexSPI_D2_A_SIGNAL                    FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
/* Routed pin properties */
#define BOARD_INITFLEXSPI_FlexSPI_D3_A_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITFLEXSPI_FlexSPI_D3_A_SIGNAL                    FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_B1_07 (coord L4), FlexSPI_CLK */
/* Routed pin properties */
#define BOARD_INITFLEXSPI_FlexSPI_CLK_PERIPHERAL                         FLEXSPI   /*!< Peripheral name */
#define BOARD_INITFLEXSPI_FlexSPI_CLK_SIGNAL                      FLEXSPI_A_SCLK   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlexSpi(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
