/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B1_08 (coord H13), AUD_INT/CSI_D9//J35[13]/J22[4] */
/* Routed pin properties */
#define BOARD_INITPINS_RED_LED_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RED_LED_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RED_LED_CHANNEL                                       24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RED_LED_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RED_LED_GPIO_PIN                                      24U   /*!< GPIO pin number */
#define BOARD_INITPINS_RED_LED_GPIO_PIN_MASK                         (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RED_LED_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RED_LED_PIN                                           24U   /*!< PORT pin number */
#define BOARD_INITPINS_RED_LED_PIN_MASK                              (1U << 24U)   /*!< PORT pin mask */

/* GPIO_AD_B1_09 (coord M13), SAI1_MCLK/CSI_D8/J35[11] */
/* Routed pin properties */
#define BOARD_INITPINS_GREEN_LED_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_GREEN_LED_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_GREEN_LED_CHANNEL                                     25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GREEN_LED_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_GREEN_LED_GPIO_PIN                                    25U   /*!< GPIO pin number */
#define BOARD_INITPINS_GREEN_LED_GPIO_PIN_MASK                       (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_GREEN_LED_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_GREEN_LED_PIN                                         25U   /*!< PORT pin number */
#define BOARD_INITPINS_GREEN_LED_PIN_MASK                            (1U << 25U)   /*!< PORT pin mask */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
/* Routed pin properties */
#define BOARD_INITPINS_BLUE_LED_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_BLUE_LED_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BLUE_LED_CHANNEL                                      10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BLUE_LED_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BLUE_LED_GPIO_PIN                                     10U   /*!< GPIO pin number */
#define BOARD_INITPINS_BLUE_LED_GPIO_PIN_MASK                        (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_BLUE_LED_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_BLUE_LED_PIN                                          10U   /*!< PORT pin number */
#define BOARD_INITPINS_BLUE_LED_PIN_MASK                             (1U << 10U)   /*!< PORT pin mask */

/* GPIO_AD_B0_09 (coord F14), JTAG_TDI/J21[5]/ENET_RST/J22[5] */
/* Routed pin properties */
#define BOARD_INITPINS_BOARD_LED_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_BOARD_LED_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOARD_LED_CHANNEL                                      9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOARD_LED_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOARD_LED_GPIO_PIN                                     9U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOARD_LED_GPIO_PIN_MASK                        (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_BOARD_LED_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_BOARD_LED_PIN                                          9U   /*!< PORT pin number */
#define BOARD_INITPINS_BOARD_LED_PIN_MASK                             (1U << 9U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_SIGNAL                             TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_SIGNAL                             RX   /*!< Signal name */

/* GPIO_AD_B1_03 (coord M12), SPDIF_IN/J22[8] */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_SPDIF_IN_PERIPHERAL                     LPUART2   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_SPDIF_IN_SIGNAL                              RX   /*!< Signal name */

/* GPIO_AD_B1_02 (coord L11), SPDIF_OUT/J22[7] */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_SPDIF_OUT_PERIPHERAL                    LPUART2   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_SPDIF_OUT_SIGNAL                             TX   /*!< Signal name */

/* GPIO_B1_13 (coord D14), WDOG_B */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_WDOG_B_PERIPHERAL                       LPUART5   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_WDOG_B_SIGNAL                                RX   /*!< Signal name */

/* GPIO_B1_12 (coord D13), SD_CD_SW */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_SD_CD_SW_PERIPHERAL                     LPUART5   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_SD_CD_SW_SIGNAL                              TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLedPins(void);

/* WAKEUP (coord L6), SD_PWREN */
/* Routed pin properties */
#define BOARD_INITKEYPINS_SD_PWREN_PERIPHERAL                              GPIO5   /*!< Peripheral name */
#define BOARD_INITKEYPINS_SD_PWREN_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITKEYPINS_SD_PWREN_CHANNEL                                    0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITKEYPINS_SD_PWREN_GPIO                                    GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITKEYPINS_SD_PWREN_GPIO_PIN                                   0U   /*!< GPIO pin number */
#define BOARD_INITKEYPINS_SD_PWREN_GPIO_PIN_MASK                      (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITKEYPINS_SD_PWREN_PORT                                    GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_INITKEYPINS_SD_PWREN_PIN                                        0U   /*!< PORT pin number */
#define BOARD_INITKEYPINS_SD_PWREN_PIN_MASK                           (1U << 0U)   /*!< PORT pin mask */

/* GPIO_AD_B0_05 (coord G14), CAN_STBY/BOOT_MODE[1]/Flash_RST/U12[8] */
/* Routed pin properties */
#define BOARD_INITKEYPINS_CAN_STBY_PERIPHERAL                              GPIO1   /*!< Peripheral name */
#define BOARD_INITKEYPINS_CAN_STBY_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITKEYPINS_CAN_STBY_CHANNEL                                    5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITKEYPINS_CAN_STBY_GPIO                                    GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITKEYPINS_CAN_STBY_GPIO_PIN                                   5U   /*!< GPIO pin number */
#define BOARD_INITKEYPINS_CAN_STBY_GPIO_PIN_MASK                      (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITKEYPINS_CAN_STBY_PORT                                    GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITKEYPINS_CAN_STBY_PIN                                        5U   /*!< PORT pin number */
#define BOARD_INITKEYPINS_CAN_STBY_PIN_MASK                           (1U << 5U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitKeyPins(void);

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
/* Routed pin properties */
#define BOARD_INITQSPI_FlexSPI_D0_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPI_FlexSPI_D0_A_SIGNAL                       FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
/* Routed pin properties */
#define BOARD_INITQSPI_FlexSPI_D1_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPI_FlexSPI_D1_A_SIGNAL                       FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
/* Routed pin properties */
#define BOARD_INITQSPI_FlexSPI_D2_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPI_FlexSPI_D2_A_SIGNAL                       FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
/* Routed pin properties */
#define BOARD_INITQSPI_FlexSPI_D3_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPI_FlexSPI_D3_A_SIGNAL                       FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_B1_07 (coord L4), FlexSPI_CLK */
/* Routed pin properties */
#define BOARD_INITQSPI_FlexSPI_CLK_PERIPHERAL                            FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPI_FlexSPI_CLK_SIGNAL                         FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B1_06 (coord L3), FlexSPI_SS0 */
/* Routed pin properties */
#define BOARD_INITQSPI_FlexSPI_SS0_PERIPHERAL                            FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPI_FlexSPI_SS0_SIGNAL                        FLEXSPI_A_SS0_B   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitQspi(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
