/*
 * norflash_partition.h
 *
 *  Created on: 2025年3月16日
 *      Author: yongjie
 */

#ifndef NORFLASH_PARTITION_H_
#define NORFLASH_PARTITION_H_

#define NOR_FLASH_SECTOR_SIZE	(4096U)


//code
#define CODE_START_ADDR 	(0x0U)
#define CODE_START_SECTOR 	(CODE_START_ADDR/NOR_FLASH_SECTOR_SIZE)
#define CODE_SIZE 			(0x200000) //2M
#define CODE_END_ADDR 		(CODE_START_ADDR+CODE_SIZE)
#define CODE_END_SECTOR		(CODE_END_ADDR/NOR_FLASH_SECTOR_SIZE)

//easyflash
#define EASYFLASH_START_ADDR 	(CODE_END_ADDR)
#define EASYFLASH_START_SECTOR 	(EASYFLASH_START_ADDR/NOR_FLASH_SECTOR_SIZE)
#define EASYFLASH_SIZE 			(0x200000) //2M
#define EASYFLASH_END_ADDR 		(EASYFLASH_START_ADDR+EASYFLASH_SIZE)
#define EASYFLASH_END_SECTOR	(EASYFLASH_END_ADDR/NOR_FLASH_SECTOR_SIZE)

//little-fs
#define LITTLE_FS_START_ADDR	(EASYFLASH_END_ADDR)
#define LITTLE_FS_START_SECTOR	(LITTLE_FS_START_ADDR/NOR_FLASH_SECTOR_SIZE)
#define LITTLE_FS_SIZE			(0x1000000)
#define LITTLE_FS_END_ADDR		(LITTLE_FS_START_ADDR+LITTLE_FS_SIZE)
#define LITTLE_FS_END_SECTOR	(LITTLE_FS_END_ADDR/NOR_FLASH_SECTOR_SIZE)

//fatfs-fs
#define FATFS_START_ADDR		(LITTLE_FS_END_ADDR)
#define FATFS_START_SECTOR		(FATFS_START_ADDR/NOR_FLASH_SECTOR_SIZE)
#define FATFS_SIZE				(0x1000000)
#define FATFS_END_ADDR			(FATFS_START_ADDR+FATFS_SIZE)
#define FATFS_END_SECTOR		(FATFS_END_ADDR/NOR_FLASH_SECTOR_SIZE)



#endif /* NORFLASH_PARTITION_H_ */
